### ISSUE TITLE
Questions about the GOOD-motif dataset

### ISSUE THREAD

**Issue by TimeLovercc** [divelab/GOOD#17]
<img width="503" alt="image" src="https://github.com/divelab/GOOD/assets/33958339/a8f114ed-5b3c-4fcd-8cbf-014bf7204ea3">
I wonder why you perform this computation just for tree. Thanks.

**Comment by CM-BF** [comment]
Because the base width of a tree is different to other base graphs. The size of tree grows exponentially with the width.
