### ISSUE TITLE
LBAPcore-Configs

### ISSUE THREAD

**Issue by ZhengtingHuang888** [divelab/GOOD#21]
Hello，Where should I get the relevant configs for running Lbapcore data？

**Comment by CM-BF** [comment]
Hi Zhengting,

Although we provide LBAP core dataset in this repo, it is not a part of our benchmark. However, you can find some LBAPcore configs in our latest work [LECI](https://github.com/divelab/LECI). Furthermore, if you hope to use other DrugOOD datasets under the GOOD architecture, please [download their datasets](https://github.com/tencent-ailab/DrugOOD) and then slightly modify the [LBAPcore data pre-processing pipeline](https://github.com/divelab/GOOD/blob/6f0a9c8be9d1ea07033a1d8dcac1144b18021ab3/GOOD/data/good_datasets/lbap_core.py#L92) to make it work.

Please let me know if you have any further questions. :)

Best,
Shurui

**Comment by ZhengtingHuang888** [comment]
OK,thanks!
