### ISSUE TITLE
Questions about the comparison graph

### ISSUE THREAD

**Issue by czstudio** [divelab/GOOD#22]
Excuse me, how can I draw a comparison graph between the visually extracted causal diagram and the actual label? such as the paper："Joint Learning of Label and Environment Causal Independence for Graph Out-of-Distribution Generalization" **F.2 Interpretability visualization results** 
"We provide interpretability [38, 98] visualization results on GOOD-Motif and CFP-Motif. As illustrated in Fig. 8..."
or 
![Snipaste_2024-01-21_10-43-21](https://github.com/divelab/GOOD/assets/23380949/a737d9f7-d1c9-44bd-aff2-f5631f638442)

Best regards

**Comment by CM-BF** [comment]
Hi @czstudio,

Hope you are doing well. These figures are draw only in synthetic datasets with causal subgraph ground truths (nodes in your examples). The overall visualization strategy is using the color of nodes to represent the causal and non-causal ground truth and using edges (different colors or bold) to illustrate the actual results.

Specifically, you can use the package `networks` to draw the figure. You may find [this code](https://github.com/divelab/LECI/blob/LECI-1.0.0/GOOD/utils/graph_visualize.py) in LECI useful.

I hope this is the answer you need. Please ask me if you have any questions.

Best,
Shurui

**Comment by czstudio** [comment]
Thank you for your prompt reply. I discovered this code. Can you provide me with a complete example to show that a causal graph is obtained after training with an OOD algorithm such as LECI or GSAT, and the [plot_graph](https://github.com/divelab/LECI/blob/LECI-1.0.0/GOOD/utils/graph_visualize.py) function is used to show it?

**Comment by CM-BF** [comment]
[Dataset visualization script](https://github.com/divelab/GOOD/blob/GOODv1/visualize_examples.py) added. Please change the color of the edges marked by the OOD algorithms to show the predicted causal graphs. : )
