### ISSUE TITLE
请问有计划加入GALA，GIL等最新的graph ood方法吗

### ISSUE THREAD

**Issue by bruno686** [divelab/GOOD#23]
如题

**Comment by CM-BF** [comment]
Hi Zhuangzhuang,

I'd love to but it really depends on my schedule. ;)

Best,
Shurui

**Comment by bruno686** [comment]
经过这一段时间使用，框架非常棒！逻辑清晰，点赞👍！祝你新年快乐！

**Comment by CM-BF** [comment]
GIL is added. This is a reproduction according to the paper. Please let me know if there is any issue. :)

**Comment by bruno686** [comment]
> GIL is added. This is a reproduction according to the paper. Please let me know if there is any issue. :)

Wow, You are so well executed!
