### ISSUE TITLE
How to fix random seeds？ 

### ISSUE THREAD

**Issue by bruno686** [divelab/GOOD#27]
Every time I run it out the results are different. Tried setting random seeds in both the args, and yaml files to no avail...

**Comment by CM-BF** [comment]
Sorry for the inconvenience. It sounds weird. Random seeds are reset in many places including the dataloader. Would you mind to 1) compare the model weights before training and 2) compare the first batch data between two runs? Once I get a moment, I will look into it.

**Comment by bruno686** [comment]
Hi Shurui, after much review, I found that the initial data is consistent for each run, but the initial weights are not. I hadn't noticed this problem before on the CBAS dataset(Model: ERM), and only on closer inspection today did I realise that on the CBAS dataset there are only very few values that are slightly different each run. But on WebKB(Model: ERM) this problem is magnified a lot, and there is almost always a large inconsistency each run. (You can try running just one epoch to quickly check the results)
