### ISSUE TITLE
INFO: pip is looking at multiple versions of wheel to determine which version is compatible with other requirements

### ISSUE THREAD

**Issue by Xuyike** [divelab/GOOD#7]
Hi GOOD authors,
    Thank you for your contribution to the research on the out of distribution generalization on the graph. I meet an issue when I install GOOD through 'pip install -e .', and it shows 'INFO: pip is looking at multiple versions of wheel to determine which version is compatible with other requirements. This could take a while'. I can't find a good solution.Are there some ways to solve this problem?

Best Regards,
xuyike

**Comment by Xuyike** [comment]
> 
I used the same version as suggested（PyTorch (==1.10.1), PyG (==2.0.3), RDKit (==2020.09.5)） to solve this problem~


> Hi GOOD authors, Thank you for your contribution to the research on the out of distribution generalization on the graph. I meet an issue when I install GOOD through 'pip install -e .', and it shows 'INFO: pip is looking at multiple versions of wheel to determine which version is compatible with other requirements. This could take a while'. I can't find a good solution.Are there some ways to solve this problem?
> 
> Best Regards, xuyike

**Comment by CM-BF** [comment]
> I used the same version as suggested（PyTorch (==1.10.1), PyG (==2.0.3), RDKit (==2020.09.5)） to solve this problem~

Excellent~ Would you like to share the version you used before when encountering the problem?

**Comment by Xuyike** [comment]
> > I used the same version as suggested（PyTorch (==1.10.1), PyG (==2.0.3), RDKit (==2020.09.5)） to solve this problem~
> 
> Excellent~ Would you like to share the version you used before when encountering the problem?

The version that caused this problem  is (PyTorch (==1.12.1), PyG (==2.1.0)).

**Comment by CM-BF** [comment]
Thanks for your info! We will test this configuration. Since the problem was solved, I'll close this issue.

**Comment by Xuyike** [comment]
> > > I used the same version as suggested（PyTorch (==1.10.1), PyG (==2.0.3), RDKit (==2020.09.5)） to solve this problem~
> > 
> > 
> > Excellent~ Would you like to share the version you used before when encountering the problem?
> 
> The version that caused this problem is (PyTorch (==1.12.1), PyG (==2.1.0)).
